### ISSUE TITLE
Receving message - Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by WahyuElfan** [WahyuElfan/visual_dart_test#4]
**Actual:**
1. When logged in as an accepting user, the side menu just loads,  check console there is an error connection closed before receiving a handshake response

**Expected:**

1. When logged in as the receiving user, it successfully displays all incoming messages

**Step to reproduce:**

1. log in as user receiving -> https://sendbird-uikit-react.netlify.app/group_channel?appId=37C8DB25-8B44-435F-A528-5BA9B9965FD0.&userId=us2&nickname=us2

![Screenshot_3501](https://github.com/WahyuElfan/visual_dart_test/assets/60707677/650cf584-9816-4b48-a4b6-55a322b7bb0c)

**Comment by luke-cha** [comment]
There is a typo in `application_id`, There is a dot(.) after `application_id`
 - Current: 37C8DB25-8B44-435F-A528-5BA9B9965FD0.
 - Fix: 37C8DB25-8B44-435F-A528-5BA9B9965FD0

**Comment by WahyuElfan** [comment]
Yes sorry, after updating the `application_id` , the problem was resolved
Thank You
